### PR TITLE
feat: Add telemac support

### LINKED ISSUE #27: Add support for telemac
pinging @tomsail

### PR DESCRIPTION
**Pull request by pmav99**
fixes #27

### CODE REVIEW

**Comment by tomsail** [comment]
looks good, thanks

**Comment by tomsail** [comment]
Since now we have the 3 option for extra dependencies, I have added info also in the README

**Comment by tomsail** [comment]
I don't have permission to this git, so I couldn't push on this branch

**Comment by tomsail** [comment]
perfect

**Comment by pmav99** [comment]
The macos ci is broken... Not sure if it is worth it to fix it though...

**Pull request merged**
